modLoader="javafml"
loaderVersion="[47,)"
license="TBD"

[[mods]]
modId="chatae"
version="${version}"
displayName="ChatAE"
description='''AE2 AI Terminal addon'''

[[dependencies.chatae]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.chatae]]
modId="architectury"
mandatory=true
versionRange="[9.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.chatae]]
modId="appliedenergistics2"
mandatory=true
versionRange="[15,)"
ordering="NONE"
side="BOTH"
