modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0"

[[mods]]
modId="mineagentae"
version="${version}"
displayName="MineAgent AE"
description='''AE2 tools and AI Terminal for MineAgent'''

[[dependencies.mineagentae]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mineagentae]]
modId="architectury"
mandatory=true
versionRange="[9.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.mineagentae]]
modId="mineagent"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.mineagentae]]
modId="ae2"
mandatory=true
versionRange="[15,)"
ordering="NONE"
side="BOTH"
