modLoader = "javafml"
loaderVersion = "*"
logoFile = "logo.png"
authors = "shartte"
license = "See GitHub repository for details"

[[mods]]
modId = "guideme"
version = "20.1.7"
displayName = "GuideME"
description = "GuideME offers the foundation for your mods or modpacks guidebook."
issueTrackerURL = "https://github.com/AppliedEnergistics/GuideME/issues"
displayURL = "https://github.com/AppliedEnergistics/GuideME/"

[[dependencies.guideme]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guideme]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
