modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0"

[[mods]]
modId="mineagentmatrix"
version="${version}"
displayName="MineAgent Matrix"
description='''Matrix bridge extension for MineAgent'''

[[dependencies.mineagentmatrix]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mineagentmatrix]]
modId="architectury"
mandatory=true
versionRange="[9.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.mineagentmatrix]]
modId="mineagent"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
