modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0"

[[mods]]
modId="chatmcmatrix"
version="${version}"
displayName="ChatMC Matrix"
description='''Matrix bridge extension for ChatMC'''

[[dependencies.chatmcmatrix]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.chatmcmatrix]]
modId="architectury"
mandatory=true
versionRange="[9.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.chatmcmatrix]]
modId="chatmc"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
