modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0"

[[mods]]
modId="mineagent"
version="${version}"
displayName="MineAgent"
description='''Minecraft AI assistant base mod'''

[[dependencies.mineagent]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.mineagent]]
modId="architectury"
mandatory=true
versionRange="[9.2,)"
ordering="NONE"
side="BOTH"
